### ISSUE TITLE
Use `core_maths` instead of `libm`

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/rustybuzz#118]
[core_maths](https://github.com/robertbastian/core_maths) should simplify `no_std` build support.
And while it has just one star, it is already used by `skrifa` and [other projects](https://crates.io/crates/core_maths/reverse_dependencies).

**Comment by CryZe** [comment]
This seems like at least a little bit of a mistake. Without any detection of whether the native libm is available, you always get slow emulated versions of all these functions now.

**Comment by LaurenzV** [comment]
Could we do:

```rs
#[cfg(not(feature = "std"))]
use core_maths::CoreFloat;
```

and something similar? Then, the `core_maths` library only gets used when `std` is explicitly disabled, while it uses the `std` one when it's enabled? It will still be in the dependency tree when using `std`, but it's still better than nothing.

**Comment by CryZe** [comment]
nvm, the fact that it's a trait with the exact same method names as the ones in `std` means that the inherent methods have higher priority in name resolution, so it should be using `std` automatically if it's available. Pretty nice solution, though not explicitly documented by them.

**Comment by RazrFalcon** [comment]
Yes, to my understanding the whole point behind `core_maths` is that it does everything automatically.

I would prefer for it to skip `libm` linking when `std` is enabled. But well. Still better then the previous solution.
