### ISSUE TITLE
rustybuzz exports symbols that conflict with harfbuzz

### ISSUE THREAD

**Issue by jneem** [RazrFalcon/rustybuzz#12]
We had a mysterious [segfault in druid](https://github.com/linebender/druid/issues/1323#issuecomment-718282421) that I tracked down to a version bump that brought in rustybuzz. I'm far from an expert on this stuff, but I noticed that after introducing the rustybuzz dep, druid started exporting symbols that clash with harfbuzz's symbols. Also, the crashes occurred on ubuntu (which has system harfbuzz version 2.6) but not on arch (which has system harfbuzz version 2.7). Could it be that rustybuzz's exported symbols are causing our problem, and if so is it possible not to export them?

**Comment by RazrFalcon** [comment]
Sorry for a delay, but rustybuzz doesn't have `hb_*` symbols. I've specifically removed all of them.

I have no idea what could be the cause of the problem.

**Comment by jneem** [comment]
Thanks for the reply! Could it be that the symbols are present in rustybuzz 0.1, but not more recent versions? The reason I ask is that if I build the `usvg` binary from git master, running `strings` on the binary gives me tons of `hb_` symbols. But if I update usvg's version of rustybuzz to 0.2, almost all of them disappear (`hb_direction` is still present for some reason). Anyway, if there was an issue here then it seems to be fixed.

**Comment by RazrFalcon** [comment]
You're right. I forgot that `usvg` still uses 0.1 and not 0.2. So yes, it will be fixed soon.
