### ISSUE TITLE
Potential fontations port?

### ISSUE THREAD

**Issue by notgull** [RazrFalcon/rustybuzz#128]
https://www.reddit.com/r/rust/comments/1e0dfj6/comment/lcobl9s/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

It was mentioned that rustybuzz could be ported to use fontations crates (e.g. skrifa, read-fonts) rather than ttf-parser. Any idea how feasible this is?

cc https://github.com/googlefonts/fontations/issues/956

**Comment by LaurenzV** [comment]
See also https://github.com/RazrFalcon/rustybuzz/pull/112#issuecomment-2183101855

**Comment by RazrFalcon** [comment]
Yes, it was extensively discussed already. We better move the discussion to https://github.com/googlefonts/fontations/issues/956
