### ISSUE TITLE
Create equivalents for `hb-view` and `hb-shape`

### ISSUE THREAD

**Issue by asibahi** [RazrFalcon/rustybuzz#130]
Hello,

It might be useful as a tool to have binaries with direct access to the shaper's internals to prototype views and ideas. Creating a command line app that just takes the font and the text and gives output is trivial, but there are a lot of different options and knobs to tweak the output.

The question is, if rustybuzz were to add equivalents (say `rb-shape` and `rb-view`, is it important to follow the same options/interface as much as we can or should it do its own thing?

You can see the different options with `$ hb-view --help-all`

**Comment by RazrFalcon** [comment]
We already have `hb-shape`: `cargo run --example shape`
As for view: #70
