### ISSUE TITLE
hb_font_t::set_variations sets wrong coordinate values for fonts with avar tables and multiple axes

### ISSUE THREAD

**Issue by maxmelander** [RazrFalcon/rustybuzz#136]
When calling `hb_font_t::set_variations`, `set_variation` in ttf-parser will be called once for each axis. 
If the font uses an avar table, `avar.map_coordinates` will be called for all axes each time `set_variation` is called. This causes the avar table to be applied multiple times to the same coordinate.

Repro:
Font: [Recursive](https://fonts.google.com/specimen/Recursive)
Variations: 
[('slnt', 0.0), ('wght', 400.0), ('CASL', 0.0), ('CRSV', 0.0), ('MONO', 0.0)]

Setting the variations in this order will cause the normalized coordinate value for 'wght' to go something like this:
```
0. Sets 'slnt'
1. Sets 'wght' to NormalizedCoordinate(2340)
1.1 AVAR table is applied and 'wght' is set to NormalizedCoordinate(4117)

2. Sets 'CASL' to NormalizedCoordinate(0)
2.1. AVAR table is applied to everything including `wght` again. `wght` is now set to NormalizedCoordinate(5221)

...
```
After the whole loop `wght` ends up with a value of NormalizedCoordinate(6593)

You can also repro this on fonts with a single variable axis like [Spline Sans](https://fonts.google.com/specimen/Spline+Sans?query=spline+sans) by calling set_variations with a bunch of variations that do not exist in the font. 

Hope this makes sense:)

**Comment by RazrFalcon** [comment]
Does `harfbuzz` produce the correct output?

**Comment by RazrFalcon** [comment]
This change breaks `in_house::variations_005` test. So it either `harfbuzz` is wrong or there is something else going on.

**Comment by LaurenzV** [comment]
I get the same result when using `coretext` as the shaper, so I don't think it's a harfbuzz issue.

**Comment by RazrFalcon** [comment]
@LaurenzV but we implement only `ot` shaper, so it should not break, no?

**Comment by LaurenzV** [comment]
Not quite sure what you mean, but when I try the suggested `ttf-parser` patch I also get a failure for `in_house::variations_005`, like you, so there seemingly is something wrong with that patch.

**Comment by LaurenzV** [comment]
Oh, I mean shaping with harfbuzz but with `--shaper=coretext`

**Comment by maxmelander** [comment]
Looking at this commit, which adds the failing test, I think the error in my patch is that I don't handle multiple axes with the same tag:
https://github.com/RazrFalcon/rustybuzz/commit/ece1cd3e2523f8f96fb3e4beaacca1a0b54cafa1

**Comment by RazrFalcon** [comment]
Yeah, TrueType is super tricky. 

The latest commit seems to be working fine. No tests are failing and that all we care about.

Can you trying adding a test to `rustybuzz`? I can help you with it. We would need to subset your font and figure out a way to trigger the issue using the `shape` example.

**Comment by maxmelander** [comment]
Yep, I can try to do that tomorrow. I'm not quite sure how to make subsets of fonts, so if you have any tips for how to easily do that let me know.

**Comment by behdad** [comment]
> Yep, I can try to do that tomorrow. I'm not quite sure how to make subsets of fonts, so if you have any tips for how to easily do that let me know.

Try `hb-subset`.

I'm interested in adding the test to HarfBuzz as well. Thanks.

**Comment by maxmelander** [comment]
Thanks:) Gave it a go now. Let me know if it makes sense to you all.

**Comment by RazrFalcon** [comment]
Published a new version.
