### ISSUE TITLE
Support something like hb_face_create_for_tables

### ISSUE THREAD

**Issue by jrmuizel** [RazrFalcon/rustybuzz#31]
This if useful on macOS where CoreText doesn't provide a way to get font data but is still nice to use for font discovery.

**Comment by RazrFalcon** [comment]
I honestly don't understand what this function is doing in the first place.

**Comment by jrmuizel** [comment]
It lets you create an hb_face that uses a callback to get the data for a particular font table.
Firefox uses it here: https://searchfox.org/mozilla-central/rev/b32d4ca055ca9cf717be480df640f8970724a0ce/gfx/thebes/gfxFontEntry.cpp#617
And Chrome uses it in a couple of places.

**Comment by RazrFalcon** [comment]
[Like this?](https://github.com/RazrFalcon/ttf-parser/blob/de42033baf2a750234c306e9ea8b575afe3ac2c0/src/lib.rs#L728)

**Comment by CryZe** [comment]
Seems like it's the same idea, but one is pull based and the other push based
