### ISSUE TITLE
unicode-script dependency needs to be bumped

### ISSUE THREAD

**Issue by chris-morgan** [RazrFalcon/rustybuzz#35]
Currently it’s using `unicode-script = "0.5"`, but src/unicode.rs is using four unicode_script::Script enum variants that are not present in 0.5.0: Chorasmian, Dives_Akuru, Khitan_Small_Script, Yezidi.

I haven’t checked 0.5.1, but they are present in 0.5.2.

Simplest patch is to bump it to "0.5.2".

**Comment by RazrFalcon** [comment]
Thanks!
