### ISSUE TITLE
Release 0.3.1 to crates.io?

### ISSUE THREAD

**Issue by tronical** [RazrFalcon/rustybuzz#36]
Hi :)

Do you have any plans on making a new release to crates.io?

**Comment by RazrFalcon** [comment]
I will take a look at it on the weekends.

**Comment by tronical** [comment]
Thank you!

**Comment by behdad** [comment]
Hey @tronical!

Is Qt rewriting on Rust? I like to hear. :)

**Comment by tronical** [comment]
Hey @behdad :). No, I don’t think Qt is doing that. But at https://github.com/sixtyfpsui/sixtyfps we’re using femtovg and rustybuzz for text. Very grateful for this awesome port!

**Comment by behdad** [comment]
> Hey @behdad :). No, I don’t think Qt is doing that. But at https://github.com/sixtyfpsui/sixtyfps we’re using femtovg and rustybuzz for text.

Cool.

> Very grateful for this awesome port!

Yes, I like how truthful to the C++ version it is.

**Comment by RazrFalcon** [comment]
Done.

Syncing with hb 2.8 will take some time, so I leave it to a next release.
