### ISSUE TITLE
Graphite Support

### ISSUE THREAD

**Issue by mimbrown** [RazrFalcon/rustybuzz#40]
It states explicitly that harbuzz's graphite support was dropped in this implementation. I understand graphite support probably seems like a lot of work for minimal returns, but has there been any consideration about adding this? I'm assuming that would involve rewriting the graphite engine in Rust.

**Comment by RazrFalcon** [comment]
Yes, any dependency must be written in Rust. Preferably, without using `unsafe`.

Graphite looks like a fairly small library, so maybe some would be willing to port it.

**Comment by mimbrown** [comment]
I would be interested in doing it but I'm a rust newbie. This wouldn't be something you'd be willing to take on, would it?

**Comment by RazrFalcon** [comment]
Maybe someday. But I will not have free time anytime soon.

**Comment by mimbrown** [comment]
That's fair.

**Comment by DemiMarie** [comment]
> I would be interested in doing it but I'm a rust newbie. This wouldn't be something you'd be willing to take on, would it?

You could try :)

**Comment by RazrFalcon** [comment]
Out of scope.
