### ISSUE TITLE
Test failed due to ambiguous python shebang

### ISSUE THREAD

**Issue by ghost** [RazrFalcon/rustybuzz#45]
*** ERROR: ambiguous python shebang in /usr/share/cargo/registry/rustybuzz-0.5.0/scripts/gen-vowel-constraints.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/share/cargo/registry/rustybuzz-0.5.0/scripts/gen-universal-table.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
mangling shebang in /usr/share/cargo/registry/rustybuzz-0.5.0/scripts/gen-unicode-norm-table.py from /usr/bin/env python3 to #!/usr/bin/python3
*** ERROR: ambiguous python shebang in /usr/share/cargo/registry/rustybuzz-0.5.0/scripts/gen-tag-table.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/share/cargo/registry/rustybuzz-0.5.0/scripts/gen-shaping-tests.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/share/cargo/registry/rustybuzz-0.5.0/scripts/gen-indic-table.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.

https://download.copr.fedorainfracloud.org/results/remilauzier/rust-unicode/fedora-rawhide-x86_64/03707746-rust-rustybuzz/builder-live.log.gz

Fedora need a precise version of python to be declare to know which one to use.

**Comment by RazrFalcon** [comment]
Why are you running those scripts on to begin with?

**Comment by alerque** [comment]
`#!/usr/bin/env python` is not an inherently bad shebang line and the *preferred* way to do this on many/most distros. Fedora is trying to be a special wall flower here by not choosing a default Python. I think it would be fair to make Fedora patch this for their build environment(s). If you change this to explicitly `python3` there will be other distros now (and likely more in the future) that break instead.
