### ISSUE TITLE
Font::from_ptr causes segfaults due to faulty transmute

### ISSUE THREAD

**Issue by CryZe** [RazrFalcon/rustybuzz#5]
```rust
    pub(crate) fn from_ptr(font: *const ffi::hb_font_t) -> &'static Font<'static> {
        unsafe { &*(font as *const Font) }
    }
```

This straight up transmutes a `hb_font_t` into a `Font`. However `hb_font_t` is not a `Font`, it's stored as a pointer in a `Font`. This causes a segfault here:

```rust
fn font_has_glyph(font: &Font, u: u32) -> bool {
    font.ttf_parser().glyph_index(char::try_from(u).unwrap()).is_some()
}
```
where it then tries to access the `ttf_parser()` from the `font`, which doesn't exist, as it's not a `Font`, but a transmuted `hb_font_t`

**Comment by RazrFalcon** [comment]
Yes, this is a pretty bad one and there no easy way to fix it. We have to wait for a first pure Rust release.

**Comment by RazrFalcon** [comment]
The repo was reset, so this was kinda fixed.
