### ISSUE TITLE
Does rusty buzz support variable fonts?

### ISSUE THREAD

**Issue by wdanilo** [RazrFalcon/rustybuzz#53]
Hi! I'm using rustybuzz both with variable and non-variable fonts. For non-variable ones, I got nice results:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1623053/188034647-32570cbd-91ee-4590-9d74-613591c64044.png">

However, for non-variable font (mplus1), the same code gives me this: 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1623053/188034731-9d1a28fe-0d6c-4a90-b404-7925b43baccd.png">

Is this a known issue/limitation? I can provide the link to the source code if needed.

**Comment by wdanilo** [comment]
Hmm, sorry for opening and closing it fast, it might be an issue with our implementation of layouting non-monospaced fonts. I'll check it out and re-open if needed.

**Comment by RazrFalcon** [comment]
No problem. And yes, we do fully support variable fonts.
