### ISSUE TITLE
How to check what is the minimum reshaping range when inserting a glyph?

### ISSUE THREAD

**Issue by wdanilo** [RazrFalcon/rustybuzz#54]
Hi, I know that [GlyphInfo::unsafe_to_break](https://docs.rs/rustybuzz/latest/rustybuzz/struct.GlyphInfo.html) exists, but I think it does not cover my use case. I want to redraw only part of a long line of text after inserting a glyph. I want to know what part of the text should be redrawn. Let's consider the input `அட0`. If I insert `்` after `ட`, then I should get `ட்` instead of  `ட`, but I do not need to redraw neither `அ` nor `0`. Is there any utility in Rustybuzz to discover it? If not, do you have any hints on how this can be done?

**Comment by RazrFalcon** [comment]
I never had such a task so no idea. And there is nothing rustybuzz to simplify this.

**Comment by wdanilo** [comment]
Gotcha! In such a case, I'm closing this topic here. Thanks for your help!

**Comment by RazrFalcon** [comment]
I would suggest asking in https://github.com/harfbuzz/harfbuzz directly and then adopting the solution to rustybuzz. After all, the API is mostly the same.

**Comment by behdad** [comment]
We have a newer glyph flag in HarfBuzz that can be used for this purpose, almost... It's called unsafe-to-concat. It's tricky to use though.

https://harfbuzz.github.io/harfbuzz-hb-buffer.html#HB-GLYPH-FLAG-UNSAFE-TO-CONCAT:CAPS
