### ISSUE TITLE
Harfbuzz-compatible C API

### ISSUE THREAD

**Issue by DemiMarie** [RazrFalcon/rustybuzz#62]
So that rustybuzz can replace harfbuzz in Pango (GNOME text rendering lib).

**Comment by DemiMarie** [comment]
> But it would definitely take some time and I have none.

Given your location I am not at all surprised you have more important tasks, and I have no right to expect you to work on this even if you _did_ have time.  I hope you and your family are safe.

**Comment by RazrFalcon** [comment]
Thanks! Maybe next year :)
