### ISSUE TITLE
why gasp table is unused in truetype font? And use in OpenType ( I can't find relate documents )

### ISSUE THREAD

**Issue by moyy** [RazrFalcon/rustybuzz#66]
[gasp — Grid-fitting and Scan-conversion Procedure Table](https://learn.microsoft.com/en-us/typography/opentype/spec/gasp)

**Comment by RazrFalcon** [comment]
I don't know. You should ask [harfbuzz](https://github.com/harfbuzz/harfbuzz) authors.

**Comment by behdad** [comment]
Can you elaborate what you mean?
