### ISSUE TITLE
Test Apple fonts on CI

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/rustybuzz#80]
To test Apple fonts and AAT features we need macOS. For legal reasons we, same as harfbuzz, cannot include Apple fonts in the repo itself.

The way harfbuzz handles this is by running macOS-specific test only on CI and using various macOS version. Then it checks hash sums of installed fonts and runs required tests.
We have to do the same.

1. We have to extend `scripts/gen-shaping-tests.py` to generate macOS-only tests with hash sum checks.
2. Extend the CI to run those tests.

**Comment by DemiMarie** [comment]
Are there FOSS fonts that use AAT?

**Comment by RazrFalcon** [comment]
Afaik, no. Only Apple uses AAT (Apple Advanced Typography), hence the name. Some parts of AAT are barely documented to begin with.

**Comment by RazrFalcon** [comment]
GitHub does provide free instances, so it's fine. Thanks.

**Comment by LaurenzV** [comment]
I think this can be closed.
